---
version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: feat
    directory: '/'
    groups:
      actions:
        patterns:
          - '*'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
