---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    groups:
      actions:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'enhancement'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
