---
'on':
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: '.'
        required: false
        type: string

jobs:
  adr-check-toc:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.jobs_run_on }}
    env:
      ADRS_VERSION: 0.3.0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-adrs@${{ env.ADRS_VERSION }}
      - name: Install adrs
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install adrs@$ADRS_VERSION
      - name: Verify that TOC is current and properly formatted
        run: diff README.md <(~/.cargo/bin/adrs generate toc --ordered)
    timeout-minutes: ${{ inputs.timeout_minutes }}
