---
"on":
  workflow_call:
    inputs:
      adrs_version:
        default: "0.3.0"
        description: The version of ADRS that will run.
        required: false
        type: string
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      toc_file:
        description: The table of contents relative to the project root
        default: docs/adr/README.md
        required: false
        type: string
      working_directory:
        description: The working directory where all jobs should be executed.
        default: "."
        required: false
        type: string

jobs:
  adr-check-toc:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    permissions:
      contents: read
      pull-requests: read
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install adrs
        run: cargo install adrs@${{ inputs.adrs_version }}
      - name: Verify that TOC is current and properly formatted
        run:
          diff ${{ inputs.toc_file }} <(~/.cargo/bin/adrs generate toc
          --ordered)
    timeout-minutes: ${{ inputs.timeout_minutes }}
