---
'on':
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: '.'
        required: false
        type: string

jobs:
  adr-check-toc:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install adr tools
        run: git clone https://github.com/npryce/adr-tools.git
      - name: 'Test for uncommitted changes'
        run: adr-tools/src/adr generate toc | diff README.md -
    timeout-minutes: ${{ inputs.timeout_minutes }}
