---
name: "checks"
permissions:
  contents: read
  pull-requests: read

"on":
  pull_request:
    branches:
      - "main"

jobs:
  prettier:
    uses: ./.github/workflows/prettier.yaml
  conventional-commit:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/conventional-commit.yaml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
