---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  markdownlint:
    uses: ./.github/workflows/markdownlint.yaml
  conventional-commit:
    uses: ./.github/workflows/conventional-commit.yaml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
