---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  conventional:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Validate PR title
        uses: 'lab42/conventional-commit@v0.2.2'
        with:
          description_regexp: '(.*)'
  markdown-lint:
    uses: ./.github/workflows/markdown-lint.yml
  pre-commit:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v4'
      - name: 'Run pre-commit'
        uses: 'pre-commit/action@v3.0.0'
