---
"on":
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      puppet_versions:
        default: '{ "versions": [ "7", "8" ] }'
        description: The versions of Puppet on which the unit tests should run.
        required: false
        type: string
      ruby_versions:
        default: '{ "versions": [ "3.1", "3.2" ] }'
        description: The versions of Ruby on which the unit tests should run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: "."
        required: false
        type: string

jobs:
  unit-tests:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    permissions:
      contents: read
      pull-requests: read
    runs-on: ${{ inputs.jobs_run_on }}
    strategy:
      matrix:
        puppet: ${{ fromJSON(inputs.puppet_versions).versions }}
        ruby: ${{ fromJSON(inputs.ruby_versions).versions }}
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v5"
      - name: "Set up Ruby ${{ matrix.ruby }}"
        uses: "ruby/setup-ruby@v1.265.0"
        env:
          BUNDLE_SILENCE_ROOT_WARNING: "1"
          BUNDLE_WITH: "development"
          PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}"
        with:
          bundler-cache: true
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "latest"
      - name: "Run unit tests"
        run:
          "bundle exec pdk test unit --puppet-version=${{ matrix.puppet }} -v"
    timeout-minutes: ${{ inputs.timeout_minutes }}
