---
'on':
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: '.'
        required: false
        type: string

jobs:
  unit-tests:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.jobs_run_on }}
    strategy:
      matrix:
        puppet:
          - '7'
          - '8'
        ruby:
          - '3.1'
          - '3.2'
    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v4'
      - name: 'Set up Ruby'
        uses: 'ruby/setup-ruby@v1.162.0'
        env:
          BUNDLE_SILENCE_ROOT_WARNING: '1'
          BUNDLE_WITH: 'development'
          PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}"
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
          rubygems: 'latest'
      - name: 'Run unit tests'
        run: 'bundle exec pdk test unit --puppet-version=${{ matrix.puppet }} -v'
    timeout-minutes: ${{ inputs.timeout_minutes }}
