---
'on':
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      puppet_version:
        default: '7'
        description: The version of Puppet to use in PDK
        required: false
        type: string
      ruby_version:
        description: The version of Ruby to use for the run.
        default: '3.2'
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: '.'
        required: false
        type: string

jobs:
  linting:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v4'
      - name: "Set up Ruby ${{ inputs.ruby_version }}"
        uses: 'ruby/setup-ruby@v1.230.0'
        env:
          BUNDLE_SILENCE_ROOT_WARNING: '1'
          BUNDLE_WITH: 'development'
          PUPPET_GEM_VERSION: "~> ${{ inputs.puppet_version }}"
        with:
          bundler-cache: true
          ruby-version: "${{ inputs.ruby_version }}"
          rubygems: 'latest'
      - name: 'Run static analysis'
        run: bundle exec pdk validate --puppet-version=${{ inputs.puppet_version }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
