---
name: pypi_test_deploy

'on':
  workflow_call:
    inputs:
      additional_packages:
        default: ''
        description: String of additional packages that should be installed.
        required: false
        type: string
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: '.'
        required: false
        type: string
    secrets:
      pypi_test_token:
        description: The PyPi for test.pypi.org token to use to deploy.
        required: true

jobs:
  pypi_test_deploy:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: Install additional packages
        if: ${{ inputs.additional_packages != '' }}
        run: sudo apt-get install -y ${{ inputs.additional_packages }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          cache: poetry
          python-version: '3.11'
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install
      - name: Setup PyPi credential
        env:
          PYPI_TOKEN: ${{ secrets.pypi_test_token }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi "$PYPI_TOKEN"
      - name: Package build
        run: poetry build
      - name: Publish package to PyPi
        run: poetry publish --dry-run -r testpypi
    timeout-minutes: ${{ inputs.timeout_minutes }}
