---
name: pypi_test_deploy

"on":
  workflow_call:
    inputs:
      additional_packages:
        default: ""
        description: String of additional packages that should be installed.
        required: false
        type: string
      environment_name:
        default: "testpypi"
        description: The name of the environment used to deploy to Test PyPi
        required: false
        type: string
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      package_name:
        default: ""
        description: The name of the package deploying to Test PyPi
        required: true
        type: string
      poetry_install_options:
        default: "--no-root"
        description: Extra options to pass to Poetry when doing an install.
        required: false
        type: string
      python_version:
        description: The version of Python to use for the run.
        default: "3.12"
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: "."
        required: false
        type: string

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    name: Build distribution 📦
    permissions:
      contents: read
      pull-requests: read
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: Install additional packages
        if: ${{ inputs.additional_packages != '' }}
        run: |
          sudo apt-get update -yq
          sudo apt-get install -y ${{ inputs.additional_packages }}
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install poetry
        run: pipx install poetry
      - name: "Set up Python ${{ inputs.python_version }}"
        uses: actions/setup-python@v6
        with:
          cache: poetry
          python-version: "${{ inputs.python_version }}"
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install ${{ inputs.poetry_install_options }}
      - name: Package build
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-test-package-distributions
          path: dist/
    timeout-minutes: ${{ inputs.timeout_minutes }}
  publish-to-testpypi:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    environment:
      name: testpypi
      url: https://test.pypi.org/p/${{ inputs.package_name }}
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - build
    permissions:
      contents: read
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      pull-requests: read
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-test-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
    timeout-minutes: ${{ inputs.timeout_minutes }}
