---
name: python-linting

'on':
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: '.'
        required: false
        type: string

jobs:
  linting:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: '3.11'
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install
      - name: Lint with yamllint
        run: poetry run yamllint . -s
      - name: Lint with pylama
        run: "poetry run pylama -v --skip '.venv/*'"
    timeout-minutes: ${{ inputs.timeout_minutes }}
