---
"on":
  workflow_call:
    inputs:
      jobs_run_on:
        default: ubuntu-latest
        description: The runner group on which jobs will run.
        required: false
        type: string
      tflint_config_path:
        default: ".tflint.hcl"
        description: The relative path to the TFlint configuration file.
        required: false
        type: string
      timeout_minutes:
        description: The maximum time (in minutes) for a job to run.
        default: 5
        required: false
        type: number
      working_directory:
        description: The working directory where all jobs should be executed.
        default: "."
        required: false
        type: string

jobs:
  linting:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    permissions:
      contents: read
      pull-requests: read
    runs-on: ${{ inputs.jobs_run_on }}
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v5"
      - name: "Setup TFLint"
        uses: "terraform-linters/setup-tflint@v6"
      - name: "Run TFLint"
        run: tflint -c ${{ inputs.tflint_config_path }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
